#!/usr/bin/env python3
"""Batch XRB spectral fitting for all 23 clusters.

Assumes blank-sky spectra have already been generated by batch_blanksky_gen.py.
Runs fit_spectral_xrb.py with --no-run-blanksky --no-run-specextract.
"""
from __future__ import annotations

import csv
import json
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from postproces_cluster import (
    CLUSTER_TABLE_PATH,
    load_cluster_configs_from_table,
    resolve_cluster_config,
)
from fit_spectral_xrb import _alt_cluster_keys

SUMMARY_CSV = Path("output/products/spectral/spectral_xrb_summary.csv")
ACCEPT_CSV = Path("configs/accept_reference.csv")


def load_accept_reference() -> dict:
    ref = {}
    if not ACCEPT_CSV.exists():
        return ref
    with open(ACCEPT_CSV) as f:
        for row in csv.DictReader(f):
            ref[row["cluster_key"]] = row
    return ref


def run_cluster(cluster_key: str, xrb_policy: str = "fixed_shape",
                fit_min_kev: float = 0.7, fit_max_kev: float = 7.0) -> dict:
    """Run fit_spectral_xrb.py for one cluster. Returns results dict."""
    script = Path(__file__).parent / "fit_spectral_xrb.py"
    cmd = [
        sys.executable, str(script),
        "--cluster", cluster_key,
        "--xrb-policy", xrb_policy,
        "--fit-min-kev", str(fit_min_kev),
        "--fit-max-kev", str(fit_max_kev),
        "--renormalize-blanksky-pha",
        "--no-run-blanksky",
        "--no-run-specextract",
    ]
    result = {"cluster_key": cluster_key, "status": "pending"}

    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
        stdout = proc.stdout + "\n" + proc.stderr

        # Parse T_X from output
        for line in stdout.split("\n"):
            if "T_X" in line and "keV" in line and "=" in line:
                parts = line.split("=")
                for j in range(len(parts) - 1):
                    try:
                        result["Tx_keV"] = float(parts[j + 1].strip().split()[0])
                    except (ValueError, IndexError):
                        pass

        # Try to find the results JSON in output/
        results_json = Path(f"output/products/spectral/{cluster_key}_results.json")
        if results_json.exists():
            with open(results_json) as f:
                d = json.load(f)
            result["Tx_keV"] = d.get("temperature_keV")
            result["Tx_err_lo"] = d.get("confidence_intervals", {}).get("icm_src.kT", {}).get("lower_delta_1sigma")
            result["Tx_err_hi"] = d.get("confidence_intervals", {}).get("icm_src.kT", {}).get("upper_delta_1sigma")
            result["rstat"] = d.get("rstat")
            result["qval"] = d.get("q_value")
            result["Lx_bol"] = d.get("bolometric_luminosity_unabsorbed_erg_s")
            result["r_em"] = d.get("r_em_annulus_to_source")
            result["n_spectra"] = len(d.get("source_spectra", []))
            result["annulus_rstat"] = d.get("annulus_fit", {}).get("rstat")
            result["qa_flags"] = d.get("qa_flags", [])

        result["status"] = "done"
        if proc.returncode != 0:
            result["status"] = "error"
            result["error"] = proc.stderr[-500:] if proc.stderr else "nonzero exit"

    except subprocess.TimeoutExpired:
        result["status"] = "timeout"
    except Exception as exc:
        result["status"] = f"error: {exc}"

    return result


def main():
    configs = load_cluster_configs_from_table(CLUSTER_TABLE_PATH)
    accept = load_accept_reference()

    with open("memory/pipeline_status.csv") as f:
        pipeline = list(csv.DictReader(f))
    pipeline_clusters = [
        row["cluster_key"] for row in pipeline
        if row.get("pipeline") == "done"
    ]

    print(f"[info] Running XRB fitting for {len(pipeline_clusters)} clusters")
    print(f"[info] Settings: xrb-policy=fixed_shape, renorm=on, band=0.7-7.0 keV")
    print()

    results = []
    for i, key in enumerate(pipeline_clusters, 1):
        try:
            _, cfg = resolve_cluster_config(key, configs)
        except SystemExit:
            print(f"[warn] {key}: missing from config table")
            continue
        z = cfg.redshift or 0
        print(f"[{i}/{len(pipeline_clusters)}] {key} (z={z:.3f})")

        t0 = time.time()
        r = run_cluster(key)
        dt = time.time() - t0

        # Add ACCEPT reference (try all naming conventions)
        acc = {}
        for k in _alt_cluster_keys(key):
            if k in accept:
                acc = accept[k]
                break
        try:
            r["accept_Tx"] = float(acc.get("accept_tx_kev", "nan"))
        except (ValueError, TypeError):
            r["accept_Tx"] = None
        r["z"] = z

        if r.get("Tx_keV") and r.get("accept_Tx"):
            r["ratio"] = r["Tx_keV"] / r["accept_Tx"]

        results.append(r)

        tx_str = f"{r.get('Tx_keV', '?'):.2f}" if isinstance(r.get('Tx_keV'), float) else str(r.get('Tx_keV', '?'))
        acc_str = f"{r.get('accept_Tx', '?'):.2f}" if isinstance(r.get('accept_Tx'), float) else str(r.get('accept_Tx', '?'))
        ratio_str = f"{r.get('ratio', '?'):.2f}" if isinstance(r.get('ratio'), float) else str(r.get('ratio', '?'))
        rstat_str = f"{r.get('rstat', '?'):.3f}" if isinstance(r.get('rstat'), float) else str(r.get('rstat', '?'))
        print(f"  T_X={tx_str} keV, ACCEPT={acc_str}, ratio={ratio_str}, rstat={rstat_str} ({dt:.0f}s)")

        if r["status"] != "done":
            print(f"  [warn] status={r['status']}")

    # Write summary CSV
    SUMMARY_CSV.parent.mkdir(parents=True, exist_ok=True)
    if results:
        fieldnames = ["cluster_key", "z", "Tx_keV", "Tx_err_lo", "Tx_err_hi",
                      "accept_Tx", "ratio", "rstat", "qval", "Lx_bol",
                      "r_em", "n_spectra", "annulus_rstat", "qa_flags", "status"]
        with open(SUMMARY_CSV, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            writer.writerows(results)
        print(f"\n[info] Summary: {SUMMARY_CSV}")

        # Stats
        good = [r for r in results if r.get("ratio") and 0.7 <= r["ratio"] <= 1.3 and isinstance(r.get("rstat"), float) and r["rstat"] < 1.5]
        ok = [r for r in results if r.get("ratio") and 0.5 <= r["ratio"] <= 1.5]
        failed = [r for r in results if r["status"] != "done"]
        print(f"  Good (0.7<ratio<1.3, rstat<1.5): {len(good)}/{len(results)}")
        print(f"  Acceptable (0.5<ratio<1.5): {len(ok)}/{len(results)}")
        if failed:
            print(f"  Failed: {[r['cluster_key'] for r in failed]}")


if __name__ == "__main__":
    main()
